export const MOCK_CLINICS = {
  name: 'My Clinic',
  optedIn: false,
  patientsShared: 0,
  accessCount: 0,
  multiplier: 0,
};

export const MOCK_PATIENTS = [
  {
    id: 1,
    name: 'John Doe',
    age: 45,
    conditions: ['Hypertension', 'Diabetes'],
    lastVisit: '2023-12-15',
  },
  {
    id: 2,
    name: 'Jane Smith',
    age: 30,
    conditions: ['Asthma'],
    lastVisit: '2024-01-05',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    age: 60,
    conditions: ['Arthritis', 'High Cholesterol'],
    lastVisit: '2023-11-20',
  },
];

export const MOCK_REQUESTS = [
  {
    id: 1,
    patientName: 'Sarah M.',
    patientCondition: 'Lower back pain',
    requestingClinic: 'Westside Health',
    reason: 'Patient visiting for second opinion on treatment plan',
    requestDate: '2026-01-26',
  },
  {
    id: 2,
    patientName: 'John D.',
    patientCondition: 'Rotator cuff injury',
    requestingClinic: 'Central Sports Rehab',
    reason: 'Patient transferred care, needs treatment history',
    requestDate: '2026-01-25',
  },
  {
    id: 3,
    patientName: 'Emily R.',
    patientCondition: 'ACL rehabilitation',
    requestingClinic: 'Northside Physio',
    reason: 'Continuing rehab program, requires progress notes',
    requestDate: '2026-01-24',
  },
  {
    id: 4,
    patientName: 'Michael T.',
    patientCondition: 'Tennis elbow',
    requestingClinic: 'Elite Sports Therapy',
    reason: 'Patient seeking specialist treatment for chronic condition',
    requestDate: '2026-01-23',
  },
  {
    id: 5,
    patientName: 'Jessica L.',
    patientCondition: 'Plantar fasciitis',
    requestingClinic: 'Westside Health',
    reason: 'Follow-up treatment after initial consultation',
    requestDate: '2026-01-23',
  },
  {
    id: 6,
    patientName: 'David K.',
    patientCondition: 'Post-surgery knee recovery',
    requestingClinic: 'Central Sports Rehab',
    reason: 'Patient relocated, continuing post-operative rehabilitation',
    requestDate: '2026-01-22',
  },
  {
    id: 7,
    patientName: 'Amanda W.',
    patientCondition: 'Neck strain',
    requestingClinic: 'Northside Physio',
    reason: 'Patient requesting second opinion on treatment approach',
    requestDate: '2026-01-22',
  },
  {
    id: 8,
    patientName: 'Robert H.',
    patientCondition: 'Sciatica',
    requestingClinic: 'Elite Sports Therapy',
    reason: 'Comprehensive treatment history needed for new care plan',
    requestDate: '2026-01-21',
  },
  {
    id: 9,
    patientName: 'Linda P.',
    patientCondition: 'Frozen shoulder',
    requestingClinic: 'Westside Health',
    reason: 'Patient traveling, needs continuity of care documentation',
    requestDate: '2026-01-21',
  },
  {
    id: 10,
    patientName: 'James B.',
    patientCondition: 'Hip bursitis',
    requestingClinic: 'Central Sports Rehab',
    reason: 'Patient referred by GP, requesting full treatment history',
    requestDate: '2026-01-20',
  },
  {
    id: 11,
    patientName: 'Patricia G.',
    patientCondition: 'Carpal tunnel syndrome',
    requestingClinic: 'Northside Physio',
    reason: 'Pre-surgery assessment requires previous treatment records',
    requestDate: '2026-01-20',
  },
  {
    id: 12,
    patientName: 'Christopher N.',
    patientCondition: 'Hamstring tear',
    requestingClinic: 'Elite Sports Therapy',
    reason: 'Sports injury assessment needs baseline treatment data',
    requestDate: '2026-01-19',
  },
  {
    id: 13,
    patientName: 'Mary S.',
    patientCondition: 'Osteoarthritis management',
    requestingClinic: 'Westside Health',
    reason: 'Long-term condition monitoring requires historical records',
    requestDate: '2026-01-19',
  },
  {
    id: 14,
    patientName: 'Daniel F.',
    patientCondition: 'Whiplash recovery',
    requestingClinic: 'Central Sports Rehab',
    reason: 'Insurance claim documentation requires complete treatment history',
    requestDate: '2026-01-18',
  },
  {
    id: 15,
    patientName: 'Elizabeth C.',
    patientCondition: 'Ankle sprain rehabilitation',
    requestingClinic: 'Northside Physio',
    reason: 'Patient returning after gap in treatment, needs continuity assessment',
    requestDate: '2026-01-18',
  },
];